// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xreiuylvjddgpmedlymu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyZWl1eWx2amRkZ3BtZWRseW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAwNzYxNjksImV4cCI6MjA3NTY1MjE2OX0.SgoIW6mTjCb7rDI6AZPuQ64vv2kGS-4uDCjuor6rRtA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});